### ISSUE TITLE
Easy

### ISSUE THREAD

**Issue by dkStephanos** [learn-co-curriculum/react-component-mounting-and-unmounting-lab#15]
This lab is remarkably easy. Not necessarily an issue, but I would have appreciated a bit more of a challenge to better learn this material. As is, you barely even code, took me about 30 seconds to complete, and it is the only lab for the entire section.

**Comment by DanielSeehausen** [comment]
Hi there,

Raising issues on GitHub should be reserved for problems with the Learn.co curriculum.

This issue is being closed now as off-topic. If you still feel that this is an issue with the curriculum, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
