### ISSUE TITLE
Bug in the code

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/react-component-mounting-and-unmounting-lab#18]
The logic for `getPancakeStatus` introduces a bug. Because it's checking `!flippedAt` instead of checking explicitly for `undefined` (ie `typeof this.state.flippedAt === 'undefined'` ), it is possible to get a truthy value for `!flippedAt` if you flip at 0 seconds. Because 0 is a falsy value in JS, if you flip @ 0 seconds and then flip the other side at two seconds, you get a return value of 'cooked' from `getPancakeStatus`. 

Also, setting something explicitly to `undefined` goes against [previous guidance in the curriculum](https://learn.co/tracks/full-stack-web-development-v6/javascript/basics/variables) (top tip halfway down the page), so if it is ok to do so in this case, it might be a good idea to add an extra sentence for an explanation. 

I would recommend checking for an explicit `undefined` value in `getPancakeStatus` instead of just a falsy value to remove the bug.

**Comment by maxwellbenton** [comment]
Hey @micahshute,

Thanks for this. Agreed, my understanding of `undefined` is that it isreally meant for the lack of return value, but not to be assigned as a value itself.

I've updated the starter code to use `null` instead and to check if `flippedAt` is a number rather than rely on `undefined`, which should prevent the misfire a zero from happening.

Thank you!
