### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by pamccombs** [learn-co-curriculum/react-component-mounting-and-unmounting-lab#29]
when I use npm start it loads the previous lab and not the new one. I'm not sure how to fix it. Maybe in package.json? The name has the previous lab's name.

**Comment by maxwellbenton** [comment]
Hi @pamccombs,

Thank you for opening this ticket. Unfortunately, I was unable to replicate the issue as you described. This name in the npm package looks like it is the correct one for this lab, but either way, this should not impact the ability to run `npm start`.

Since `npm start` seems to be working, I am going to close this issue for now, but if you have any additional information regarding this issue or how to replicate it, please feel free to re-open this issue and I will take another look.

Thank you!
